name: Publish to dev.to

on:
  push:
    branches:
      - url-forwarding

jobs:
  publish:
    if: "!contains(github.event.head_commit.message, 'Add article ID to latest article')"
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Find latest article by commit date
      run: |
        latest_article=$(git log -1 --pretty=format: --name-only -- content/blogs/**/*.md | grep -v '_index.md' | head -n 1)
        if [ -z "$latest_article" ]; then
          echo "No article found"
          exit 1
        fi
        cp "$latest_article" latest_article.md

    - name: Replace relative paths with GitHub raw content URLs
      run: |
        repo_url="https://raw.githubusercontent.com/${{ github.repository }}/main/"
        sed -i "s|./|$repo_url|g" latest_article.md

    - name: Extract title from article
      run: |
        title=$(grep -m 1 '^# ' latest_article.md | sed 's/^# //')
        description=$(grep -m 1 '^description: ' latest_article.md | sed 's/^description: //')
        tags=$(grep -m 1 '^tags: ' latest_article.md | sed 's/^tags: //' | jq -R 'split(",")' | jq -c '.')
        echo "title: $title" >> latest_article.md
        echo "description: $description" >> latest_article.md
        echo "tags: $tags" >> latest_article.md

    - name: Publish to dev.to
      env:
        DEVTO_API_KEY: ${{ secrets.DEVTO_API_KEY }}
      run: |
        request_body=$(cat <<EOF
        {
          "article": {
            "title": "$title",
            "description": "$description",
            "tags": $tags,
            "published": true,
            "body_markdown": "$(cat latest_article.md)"
          }
        }
        EOF
        )
        echo "$request_body"
        response=$(curl -X POST \
          -H "Content-Type: application/json" \
          -H "api-key: " \
          -d "$request_body" https://dev.to/api/articles)
        article_id=$(echo $response | jq -r '.id')
        echo "id: $article_id" | cat - latest_article.md > temp && mv temp latest_article.md
        echo "id: $article_id" | cat - $latest_article > temp && mv temp $latest_article

    - name: Commit changes
      run: |
        echo "Article body before committing:"
        cat latest_article.md
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add $latest_article
        git commit -m "Add article ID to latest article [skip ci]"
        git push origin main