name: Publish to dev.to

on:
  push:
    branches:
      - master

jobs:
  publish:
    if: "!contains(github.event.head_commit.message, 'Add article ID to latest article')"
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install requests pyyaml

    - name: Process markdown with Python
      env:
        GITHUB_WORKSPACE: ${{ github.workspace }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        GITHUB_REF_NAME: ${{ github.ref_name }}
        DEVTO_API_KEY: ${{ secrets.DEVTO_API_KEY }}
      run: |
        python process_markdown.py

    - name: Commit changes
      run: |
        echo "Article body before committing:"
        cat latest_article.md
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add $latest_article
        git commit -m "Add article ID to latest article [skip ci]"
        git push origin main