name: Publish to dev.to

on:
  push:
    branches:
      - url-forwarding

jobs:
  publish:
    if: "!contains(github.event.head_commit.message, 'Add article ID to latest article')"
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Find latest article by commit date
      run: |
        cd $GITHUB_WORKSPACE
        latest_article=$(git log -1 --pretty=format: --name-only -- content/blogs/**/*.md | grep -v 'content/blogs/_index.md' | head -n 1)
        if [ -z "$latest_article" ]; then
          echo "No article found"
          exit 1
        fi
        cp "$latest_article" latest_article.md

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install requests pyyaml

    - name: Process markdown with Python
      run: |
        python process_markdown.py

    - name: Commit changes
      run: |
        echo "Article body before committing:"
        cat latest_article.md
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add $latest_article
        git commit -m "Add article ID to latest article [skip ci]"
        git push origin main